enum NativeFieldSubcategory : short
{
    NATIVE_FIELD_CATEGORY_FLOAT = 1 << 8,
    NATIVE_FIELD_SUBCATEGORY_NESTED = 1 << 9,
    NATIVE_FIELD_CATEGORY_COM_ONLY = 1 << 10,
    NATIVE_FIELD_CATEGORY_COM_TYPE = 1 << 11,
    NATIVE_FIELD_SUBCATEGORY_INTEGER = 1 << 12,
    NATIVE_FIELD_SUBCATEGORY_ARRAY = 1 << 13
};

enum NativeFieldCategory : short
{
    NATIVE_FIELD_CATEGORY_R4 = NATIVE_FIELD_CATEGORY_FLOAT,
    NATIVE_FIELD_CATEGORY_R8 = NATIVE_FIELD_CATEGORY_FLOAT | 0x1,
    NATIVE_FIELD_CATEGORY_NESTED_TYPE = NATIVE_FIELD_SUBCATEGORY_NESTED,
    NATIVE_FIELD_CATEGORY_DATE = NATIVE_FIELD_CATEGORY_R8 | NATIVE_FIELD_CATEGORY_COM_TYPE,
    NATIVE_FIELD_CATEGORY_IN_PLACE_ARRAY = NATIVE_FIELD_SUBCATEGORY_ARRAY | NATIVE_FIELD_SUBCATEGORY_NESTED,
    NATIVE_FIELD_CATEGORY_INTEGER_LIKE = NATIVE_FIELD_SUBCATEGORY_INTEGER,
    NATIVE_FIELD_CATEGORY_SAFE_ARRAY = NATIVE_FIELD_CATEGORY_COM_ONLY,
    NATIVE_FIELD_CATEGORY_INTERFACE_TYPE = NATIVE_FIELD_CATEGORY_COM_ONLY | 0x1,
    NATIVE_FIELD_CATEGORY_COM_STRUCT = NATIVE_FIELD_CATEGORY_COM_ONLY | NATIVE_FIELD_SUBCATEGORY_INTEGER,
    NATIVE_FIELD_CATEGORY_OTHER = 0x1
};
