enum NativeFieldSubcategory
{
    NATIVE_FIELD_CATEGORY_FLOAT = 1 << 10,
    NATIVE_FIELD_SUBCATEGORY_NESTED = 1 << 11,
#ifdef FEATURE_COMINTEROP
    NATIVE_FIELD_CATEGORY_COM_ONLY = 1 << 12,
#endif // FEATURE_COMINTEROP
    NATIVE_FIELD_CATEGORY_COM_TYPE = 1 << 13,
    NATIVE_FIELD_SUBCATEGORY_INTEGER = 1 << 14,
    NATIVE_FIELD_SUBCATEGORY_ARRAY = 1 << 15
};

enum NativeFieldCategory
{
    NATIVE_FIELD_CATEGORY_R4 = NATIVE_FIELD_CATEGORY_FLOAT,
    NATIVE_FIELD_CATEGORY_R8 = NATIVE_FIELD_CATEGORY_FLOAT | 0x1,
    NATIVE_FIELD_CATEGORY_NESTED_TYPE = NATIVE_FIELD_SUBCATEGORY_NESTED,
    NATIVE_FIELD_CATEGORY_DATE = NATIVE_FIELD_CATEGORY_R8 | NATIVE_FIELD_CATEGORY_COM_TYPE,
    NATIVE_FIELD_CATEGORY_IN_PLACE_ARRAY = NATIVE_FIELD_SUBCATEGORY_ARRAY | NATIVE_FIELD_SUBCATEGORY_NESTED,
    NATIVE_FIELD_CATEGORY_INTEGER_LIKE = NATIVE_FIELD_SUBCATEGORY_INTEGER,
#ifdef FEATURE_COMINTEROP
#ifdef FEATURE_CLASSIC_COMINTEROP
    NATIVE_FIELD_CATEGORY_SAFE_ARRAY = NATIVE_FIELD_CATEGORY_COM_ONLY,
#endif // FEATURE_CLASSIC_COMINTEROP
    NATIVE_FIELD_CATEGORY_INTERFACE_TYPE = NATIVE_FIELD_CATEGORY_COM_ONLY | 0x1,
    NATIVE_FIELD_CATEGORY_COM_STRUCT = NATIVE_FIELD_CATEGORY_COM_ONLY | NATIVE_FIELD_SUBCATEGORY_INTEGER,
#endif // FEATURE_COMINTEROP
    NATIVE_FIELD_CATEGORY_OTHER = 0
};
