parameters:
  buildConfig: ''
  archType: ''
  osGroup: ''
  osSubgroup: ''
  container: ''
  testGroup: ''
  crossrootfsDir: ''
  # If true, run the corefx tests instead of the coreclr ones
  corefxTests: false
  displayNameArgs: ''
  condition: true
  stagedBuild: false
  priBuildNamePart: ''
  priDisplayNamePart: ''

### Build managed test components (native components are getting built as part
### of the the product build job).

### TODO: As of today, build of managed test components requires the product build
### as a prerequisite due to dependency on System.Private.Corelib. After switching
### over to its reference assembly we should be able to remove this dependency and
### run managed test builds in parallel with the product build job.

jobs:
- template: xplat-test-job.yml
  parameters:
    buildConfig: ${{ parameters.buildConfig }}
    archType: ${{ parameters.archType }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    managedTestBuildOsGroup: ${{ parameters.osGroup }}
    managedTestBuildOsSubgroup: ${{ parameters.osSubgroup }}
    managedTestBuildArchType: ${{ parameters.archType }}
    container: ${{ parameters.container }}
    testGroup: ${{ parameters.testGroup }}
    corefxTests: ${{ parameters.corefxTests }}
    stagedBuild: ${{ parameters.stagedBuild }}

    # Test jobs should continue on error for internal builds
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      continueOnError: true

    # Compute job name from template parameters
    name: 'build_test_${{ parameters.priBuildNamePart }}${{ parameters.displayNameArgs }}_${{ parameters.osGroup }}${{ parameters.osSubgroup }}_${{ parameters.archType }}_${{ parameters.buildConfig }}'
    displayName: 'Build Test ${{ parameters.priDisplayNamePart }}${{ parameters.displayNameArgs }} ${{ parameters.osGroup }}${{ parameters.osSubgroup }} ${{ parameters.archType }} ${{ parameters.buildConfig }}'

    crossrootfsDir: ${{ parameters.crossrootfsDir }}

    variables:
    - name: testhostArg
      value: ''
    - ${{ if eq(parameters.corefxTests, true) }}:
      - ${{ if ne(parameters.osGroup, 'Windows_NT') }}:
        - name: testhostArg
          value: 'generatetesthostonly'
      - ${{ if eq(parameters.osGroup, 'Windows_NT') }}:
        - name: testhostArg
          value: 'buildtesthostonly'

    # Since the condition is being altered, merge the default with the additional conditions.
    # See https://docs.microsoft.com/azure/devops/pipelines/process/conditions
    condition: and(succeeded(), ${{ parameters.condition }})

    # TODO: Build of managed test components currently depends on the corresponding build job
    # because it needs System.Private.Corelib; we should be able to remove this dependency
    # by switching over to using reference assembly.
    ${{ if ne(parameters.stagedBuild, true) }}:
      dependsOn: ${{ format('build_{0}{1}_{2}_{3}', parameters.osGroup, parameters.osSubgroup, parameters.archType, parameters.buildConfig) }}

    ${{ if eq(parameters.testGroup, 'innerloop') }}:
      timeoutInMinutes: 90

    ${{ if ne(parameters.testGroup, 'innerloop') }}:
      timeoutInMinutes: 160

    steps:

    # Install test build dependencies
    - ${{ if eq(parameters.osGroup, 'OSX') }}:
      - script: sh eng/install-native-dependencies.sh $(osGroup)
        displayName: Install native dependencies
    - ${{ if eq(parameters.osGroup, 'Windows_NT') }}:
      # Necessary to install correct cmake version
      - script: eng\common\init-tools-native.cmd -InstallDirectory $(Build.SourcesDirectory)\native-tools -Force
        displayName: Install native dependencies


    # Download product binaries directory
    - template: /eng/download-artifact-step.yml
      parameters:
        downloadFolder: '$(productBuildRootFolderPath)/tmp'
        unpackFolder: '$(productBuildRootFolderPath)'
        cleanUnpackFolder: false
        artifactFileName: '$(productBuildArtifactName)$(archiveExtension)'
        artifactName: '$(productBuildArtifactName)'
        displayName: 'product build'


    # Build managed test components
    - ${{ if ne(parameters.osGroup, 'Windows_NT') }}:
      - script: ./build-test.sh skipnative skipgeneratelayout $(buildConfig) $(archType) $(crossArg) $(priorityArg) $(testhostArg) ci
        displayName: Build managed test components
    - ${{ if eq(parameters.osGroup, 'Windows_NT') }}:
      - script: build-test.cmd skipnative skipgeneratelayout $(buildConfig) $(archType) $(priorityArg) $(testhostArg) ci
        displayName: Build managed test components


    # Zip and publish managed test components
    - template: /eng/upload-artifact-step.yml
      parameters:
        rootFolder: $(testRootFolderPath)
        includeRootFolder: false
        archiveFile: '$(Build.StagingDirectory)/$(testArtifactName)$(archiveExtension)'
        archiveType: $(archiveType)
        tarCompression: $(tarCompression)
        artifactName: $(testArtifactName)
        displayName: 'managed test components'


    # Publish .packages/microsoft.net.sdk.il needed for traversing
    # test projects during the copynativeonly command in run test job.
    - ${{ if ne(parameters.corefxTests, true) }}:
      - template: /eng/upload-artifact-step.yml
        parameters:
          rootFolder: $(microsoftNetSdkIlFolderPath)
          includeRootFolder: false
          archiveFile: $(Build.StagingDirectory)/$(microsoftNetSdkIlArtifactName)$(archiveExtension)
          archiveType: $(archiveType)
          tarCompression: $(tarCompression)
          artifactName: $(microsoftNetSdkIlArtifactName)
          displayName: 'Microsoft.NET.Sdk.IL package'


    # Publish Logs
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        pathtoPublish: $(Build.SourcesDirectory)/bin/Logs
        ${{ if eq(parameters.corefxTests, true) }}:
          artifactName: ${{ format('TestBuildLogs_corefx_{0}{1}_{2}_{3}_{4}', parameters.osGroup, parameters.osSubgroup, parameters.archType, parameters.buildConfig, parameters.testGroup) }}
        ${{ if ne(parameters.corefxTests, true) }}:
          artifactName: ${{ format('TestBuildLogs_{0}{1}_{2}_{3}_{4}', parameters.osGroup, parameters.osSubgroup, parameters.archType, parameters.buildConfig, parameters.testGroup) }}
      continueOnError: true
      condition: always()
