parameters:
  # Optional: dependencies of the job
  dependsOn: ''

  artifactsDir: $(Build.StagingDirectory)/artifacts

  gitHubUser: dotnet-build-bot
  gitHubEmail: dotnet-build-bot@microsoft.com
  gitHubAuthToken: $(AccessToken-dotnet-build-bot-public-repo)

  versionsRepoOwner: dotnet
  versionsRepo: versions

jobs:
  - template: /eng/common/templates/job/publish-build-assets.yml
    parameters:
      configuration: Release
      pool:
        name: NetCore1ESPool-Svc-Internal
        demands: ImageOverride -equals windows.vs2017.amd64
      dependsOn: ${{ parameters.dependsOn }}
      publishUsingPipelines: true
