parameters:
  buildConfig: ''
  archType: ''
  osGroup: ''
  osIdentifier: ''
  containerName: ''
  crossrootfsDir: ''
  timeoutInMinutes: ''

### Format job
jobs:
- template: xplat-job.yml
  parameters:
    buildConfig: ${{ parameters.buildConfig }}
    archType: ${{ parameters.archType }}
    osGroup: ${{ parameters.osGroup }}
    osIdentifier: ${{ parameters.osIdentifier }}
    containerName: ${{ parameters.containerName }}
    crossrootfsDir: ${{ parameters.crossrootfsDir }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        packageType: 'sdk'
        version: '2.1.402'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.x'
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: $(Build.SourcesDirectory)/tests/scripts/format.py
        arguments: '-c $(Build.SourcesDirectory) -o $(osGroup) -a $(archType)'
    - task: PublishBuildArtifacts@1
      displayName: Publish format.patch
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/format.patch'
        ArtifactName: $(osGroup).$(archType) format.patch
      continueOnError: true
      condition: always()
