parameters:
  jobTemplate: ''
  buildConfig: ''
  platforms: []
  # platformGroup is a named collection of platforms. Allowed values:
  # 'all' - all platforms
  # 'gcstress' - platforms that support running under GCStress0x3 and GCStress0xC scenarios
  platformGroup: ''
  # helixQueueGroup is a named collection of Helix Queues. If specified, it determines which Helix queues are
  # used, instead of the usual criteria. Allowed values:
  # 'pr' - the queues used for a pull request for the platform. Typically a small set.
  # 'ci' - the queues used for a CI (post-merge) test run.
  # 'all' - the queues used for non-PR, non-CI test runs, e.g., Manual or Scheduled runs. Typically this is all available queues.
  # 'corefx' - the queues used for a corefx test run.
  helixQueueGroup: 'pr'
  ignoreDependencyOnBuildJobs: false
  combos: {}
  jobParameters: {}

jobs:

# TODO: simplify osIdentifier by adding osGroup and osSubGroup. See
# https://github.com/Microsoft/azure-pipelines-yaml/pull/46 for more information

# Linux arm

- ${{ if parameters.combos.linuxArm }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: arm
      osGroup: Linux
      osIdentifier: Linux
      managedBuildOsGroup: Linux
      managedBuildOsIdentifier: Linux
      container:
        image: ubuntu-16.04-cross-14.04-23cacb0-20190528233931
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Ubuntu.1804.Arm32.Open)Ubuntu.1604.Arm32.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Debian.9.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-74c9941-20190620155841
        - (Ubuntu.1604.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm32v7-30f6673-20190814153219
        - (Ubuntu.1804.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226
      crossrootfsDir: '/crossrootfs/arm'
      ${{ insert }}: ${{ parameters.jobParameters }}

# Linux arm64

- ${{ if parameters.combos.linuxArm64 }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: arm64
      osGroup: Linux
      osIdentifier: Linux
      managedBuildOsGroup: Linux
      managedBuildOsIdentifier: Linux
      container:
        image: ubuntu-16.04-cross-arm64-cfdd435-20190520220848
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Ubuntu.1804.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), notIn(parameters.helixQueueGroup, 'pr', 'ci', 'corefx')) }}:
        - (Debian.9.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-74c9941-20190620155840
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Debian.9.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-74c9941-20190620155840
        - (Ubuntu.1804.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
      crossrootfsDir: '/crossrootfs/arm64'
      ${{ insert }}: ${{ parameters.jobParameters }}

# Linux musl x64

- ${{ if parameters.combos.linuxMuslX64 }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: x64
      osGroup: Linux
      osIdentifier: Linux_musl
      ${{ if parameters.combos.osxX64 }}:
        managedBuildOsGroup: OSX
        managedBuildOsIdentifier: OSX
      ${{ if and(not(parameters.combos.osxX64), parameters.combos.linuxX64) }}:
        managedBuildOsGroup: Linux
        managedBuildOsIdentifier: Linux
      ${{ if and(not(parameters.combos.osxX64), not(parameters.combos.linuxX64)) }}:
        managedBuildOsGroup: Linux
        managedBuildOsIdentifier: Linux_musl
      container:
        image: alpine-3.6-WithNode-cfdd435-20190521001804
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Alpine.38.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-09ca40b-20190508143246
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Alpine.38.Amd64)ubuntu.1604.amd64@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-09ca40b-20190508143246
        - (Alpine.39.Amd64)ubuntu.1604.amd64@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-helix-09ca40b-20190508143246
      ${{ insert }}: ${{ parameters.jobParameters }}

# Linux musl arm64

- ${{ if parameters.combos.linuxMuslArm64 }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: arm64
      osGroup: Linux
      osIdentifier: Linux_musl
      managedBuildOsGroup: Linux
      ${{ if parameters.combos.linuxArm64 }}:
        managedBuildOsIdentifier: Linux
      ${{ if not(parameters.combos.linuxArm64) }}:
        managedBuildOsIdentifier: Linux_musl
      container:
        image: ubuntu-16.04-cross-arm64-alpine-406629a-20190520220848
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Alpine.38.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Alpine.38.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-a45aeeb-20190620184035
      crossrootfsDir: '/crossrootfs/arm64'
      ${{ insert }}: ${{ parameters.jobParameters }}

# Linux rhel6 x64

- ${{ if parameters.combos.linuxRhel6X64 }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: x64
      osGroup: Linux
      osIdentifier: Linux_rhel6
      ${{ if parameters.combos.osxX64 }}:
        managedBuildOsGroup: OSX
        managedBuildOsIdentifier: OSX
      ${{ if and(not(parameters.combos.osxX64), parameters.combos.linuxX64) }}:
        managedBuildOsGroup: Linux
        managedBuildOsIdentifier: Linux
      ${{ if and(not(parameters.combos.osxX64), not(parameters.combos.linuxX64), parameters.combos.linuxMuslX64) }}:
        managedBuildOsGroup: Linux
        managedBuildOsIdentifier: Linux_musl
      ${{ if and(not(parameters.combos.osxX64), not(parameters.combos.linuxX64), not(parameters.combos.linuxMuslX64)) }}:
        managedBuildOsGroup: Linux
        managedBuildOsIdentifier: Linux_rhel6
      container:
        image: centos-6-3e800f1-20190501005338
        registry: mcr
      helixQueues:
      # TODO: enable RedHat.6.Amd64.Open once https://github.com/dotnet/coreclr/issues/23580 is resolved
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - RedHat.6.Amd64
      ${{ insert }}: ${{ parameters.jobParameters }}
