parameters:
  jobTemplate: ''
  buildConfig: ''
  platforms: []
  # platformGroup is a named collection of platforms. Allowed values:
  # 'all' - all platforms
  # 'gcstress' - platforms that support running under GCStress0x3 and GCStress0xC scenarios
  platformGroup: ''
  # helixQueueGroup is a named collection of Helix Queues. If specified, it determines which Helix queues are
  # used, instead of the usual criteria. Allowed values:
  # 'pr' - the queues used for a pull request for the platform. Typically a small set.
  # 'ci' - the queues used for a CI (post-merge) test run.
  # 'all' - the queues used for non-PR, non-CI test runs, e.g., Manual or Scheduled runs. Typically this is all available queues.
  helixQueueGroup: 'pr'
  jobParameters: {}

jobs:

# TODO: simplify osIdentifier by adding osGroup and osSubGroup. See
# https://github.com/Microsoft/azure-pipelines-yaml/pull/46 for more information


# Linux x64

- ${{ if containsValue(parameters.platforms, 'Linux_x64') }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      buildConfig: ${{ parameters.buildConfig }}
      archType: x64
      osGroup: Linux
      osIdentifier: Linux
      container:
        image: centos-7-3e800f1-20190501005343
        registry: mcr
      helixQueues:
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest', 'IndividualCI', 'BatchedCI')) }}:
          - Ubuntu.1804.Amd64.Open
      ${{ insert }}: ${{ parameters.jobParameters }}

# Windows x64

- ${{ if or(containsValue(parameters.platforms, 'Windows_NT_x64'), in(parameters.platformGroup, 'all', 'gcstress')) }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      buildConfig: ${{ parameters.buildConfig }}
      archType: x64
      osGroup: Windows_NT
      osIdentifier: Windows_NT
      helixQueues:
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest', 'IndividualCI', 'BatchedCI')) }}:
        - ${{ if not(contains(parameters.jobTemplate, 'perf')) }}:
          - Windows.10.Amd64.Open
        - ${{ if contains(parameters.jobTemplate, 'perf') }}:
          - Windows.10.Amd64.ClientRS4.DevEx.15.8.Open
      ${{ insert }}: ${{ parameters.jobParameters }}
