parameters:
  jobTemplate: ''
  buildConfig: ''
  platforms: []
  # platformGroup is a named collection of platforms. Allowed values:
  # 'all' - all platforms
  # 'gcstress' - platforms that support running under GCStress0x3 and GCStress0xC scenarios
  platformGroup: ''
  # helixQueueGroup is a named collection of Helix Queues. If specified, it determines which Helix queues are
  # used, instead of the usual criteria. Allowed values:
  # 'pr' - the queues used for a pull request for the platform. Typically a small set.
  # 'ci' - the queues used for a CI (post-merge) test run.
  # 'all' - the queues used for non-PR, non-CI test runs, e.g., Manual or Scheduled runs. Typically this is all available queues.
  # 'corefx' - the queues used for a corefx test run.
  helixQueueGroup: 'pr'
  ignoreDependencyOnBuildJobs: false
  combos: {}
  jobParameters: {}

jobs:

# TODO: simplify osIdentifier by adding osGroup and osSubGroup. See
# https://github.com/Microsoft/azure-pipelines-yaml/pull/46 for more information

# Linux arm

- ${{ if parameters.combos.linuxArm }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: arm
      osGroup: Linux
      osIdentifier: Linux
      managedBuildOsGroup: Linux
      managedBuildOsIdentifier: Linux
      container:
        image: ubuntu-16.04-cross-14.04-23cacb0-20190528233931
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Ubuntu.1804.Arm32.Open)Ubuntu.1604.Arm32.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Debian.9.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-74c9941-20190620155841
        - (Ubuntu.1604.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm32v7-30f6673-20190814153219
        - (Ubuntu.1804.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226
      crossrootfsDir: '/crossrootfs/arm'
      ${{ insert }}: ${{ parameters.jobParameters }}

# Linux arm64

- ${{ if parameters.combos.linuxArm64 }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      ignoreDependencyOnBuildJobs: ${{ parameters.ignoreDependencyOnBuildJobs }}
      buildConfig: ${{ parameters.buildConfig }}
      archType: arm64
      osGroup: Linux
      osIdentifier: Linux
      managedBuildOsGroup: Linux
      managedBuildOsIdentifier: Linux
      container:
        image: ubuntu-16.04-cross-arm64-cfdd435-20190520220848
        registry: mcr
      helixQueues:
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - (Ubuntu.1804.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), notIn(parameters.helixQueueGroup, 'pr', 'ci', 'corefx')) }}:
        - (Debian.9.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-74c9941-20190620155840
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        - (Debian.9.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-74c9941-20190620155840
        - (Ubuntu.1804.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
      crossrootfsDir: '/crossrootfs/arm64'
      ${{ insert }}: ${{ parameters.jobParameters }}
