trigger:
- master

pr: none

jobs:


#
# Release builds
#
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64


- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: perf-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64
