trigger: none

pr: none

jobs:
#
# Checkout repository
#
- template: /eng/checkout-job.yml

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - OSX_x64
    - Windows_NT_x64
    helixQueueGroup: pr
    jobParameters:
      testGroup: innerloop

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-test-job.yml
    buildConfig: checked
    platforms:
    - OSX_x64
    - Windows_NT_x64
    helixQueueGroup: pr
    jobParameters:
      testGroup: innerloop

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: run-test-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - OSX_x64
    - Windows_NT_x64
    helixQueueGroup: pr
    jobParameters:
      testGroup: innerloop
      readyToRun: true
      crossgen2: true
      displayNameArgs: R2R_CG2
