trigger: none

pr: none

schedules:
- cron: "0 21 * * 6,0"
  displayName: Sat and Sun at 1:00 PM (UTC-8:00)
  branches:
    include:
    - master
  always: true

jobs:
#
# Checkout repository
#
- template: templates/checkout-job.yml

- template: templates/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platformGroup: gcstress
    jobParameters:
      testGroup: gcstress-extra

- template: templates/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platformGroup: gcstress
    helixQueueGroup: ci
    jobParameters:
      testGroup: gcstress-extra
