trigger:
  batch: true
  branches:
    include:
    - internal/release/3.1-crossdac

pr: none

variables:
- name: _DotNetArtifactsCategory
  value: CORECLR
- name: CrossDacCoreClrVersion
  value: 'latest'
- name: SymStoreCrossDacIndex
  value: 'false'

stages:
  - stage: Prepare
    jobs:
    #
    # Cross-dac prepare
    #
    - template: /eng/platform-matrix.yml
      parameters:
        jobTemplate: build-crossdac-job.yml
        buildConfig: release
        platforms:
        - Linux_arm64 # Needs an ubuntu container
        jobParameters:
          coreClrBuildId: variables['CrossDacCoreClrVersion']

  - stage: Build
    jobs:
    #
    # Cross-dac build
    #
    - template: /eng/platform-matrix.yml
      parameters:
        jobTemplate: build-crossdac-job.yml
        buildConfig: release
        dependsOn:
        - build_Linux_arm64_release
        platforms:
        - Windows_NT_arm
        - Windows_NT_arm64
        - Windows_NT_x64
        jobParameters:
          # Publishing packages to blob feeds sometimes takes a long time
          # due to waiting for an exclusive lock on the feed.
          # See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md
          timeoutInMinutes: 120
          coreClrBuildId: variables['CrossDacCoreClrVersion']
          symStoreCrossDacIndex: variables['SymStoreCrossDacIndex']

    #
    # Publish build information to Build Assets Registry
    #
    # This job gathers build assets from the pipeline (from each official
    # product build job), and publishes them to the build assets
    # registry. Its dependencies should be updated to include all of the
    # official builds if we add more platform/arch combinations.
    - template: /eng/finalize-publish.yml
      parameters:
        dependsOn:
        - build_Windows_NT_x64_release
        - build_Windows_NT_arm_release
        - build_Windows_NT_arm64_release

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/post-build/post-build.yml
      parameters:
        # Symbol validation is not entirely reliable as of yet, so should be turned off until https://github.com/dotnet/arcade/issues/2871 is resolved.
        enableSymbolValidation: false
