trigger:
  batch: true
  branches:
    include:
    - master

pr: none

jobs:
#
# Checkout repository
#
- template: scripts/checkout-job.yml

- template: scripts/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    jobParameters:
      testGroup: perf
    
- template: scripts/platform-matrix.yml
  parameters:
    jobTemplate: perf-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    jobParameters:
      testGroup: perf
