trigger: none

pr:
- master
- release/2.1
- release/2.2
- release/3.0

jobs:

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: release
    platforms:
    - Windows_NT_x64

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: release
    platforms:
    - Windows_NT_x64
    jobParameters:
      baseline: true
    
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: perf-job.yml
    buildConfig: release
    platforms:
    - Windows_NT_x64
    jobParameters:
      compare: true
      