trigger: none

pr:
- master
- release/2.1
- release/2.2
- release/3.0
- release/3.1

jobs:
#
# Checkout repository
#
- template: templates/checkout-job.yml

- template: templates/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - OSX_x64
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop

- template: templates/platform-matrix.yml
  parameters:
    jobTemplate: build-test-job.yml
    buildConfig: checked
    platforms:
    - OSX_x64
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop

- template: templates/platform-matrix.yml
  parameters:
    jobTemplate: run-test-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - OSX_x64
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop
      readyToRun: true
      crossgen2: true
      displayNameArgs: R2R_CG2
